# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-02 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20180101_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
